version: '3.9'

services:
    db:
        image: postgres:13-alpine
        restart: unless-stopped
        volumes:
            - pg_data:/var/lib/postgresql/data/
        ports:
            - "5431:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=Lush3-1Chaos
            - POSTGRES_DB=netology_async
volumes:
    pg_data:
